### ISSUE TITLE
关于您使用的benchmarks

### ISSUE THREAD

**Issue by acmisxuyutian** [guosyjlu/DS-Agent#3]
我去了解了一下您benchmarks中的几个竞赛数据，发现您似乎只用到了竞赛中的训练数据。就想找您请教两个问题：
1. 是否只是使用了Kaggle竞赛的训练数据，并做了一些删减？
2. benchmarks中的test数量怎么好多都比train+valid仅多一条，是出于什么考虑呢？
![image](https://github.com/guosyjlu/DS-Agent/assets/113601978/1cbcdd56-3a57-432a-bacd-a717f718d4c3)
我对机器学习不是很熟悉，不太明白，还望大佬解惑。感谢！

**Comment by guosyjlu** [comment]
你好，
1. 是的：因为Kaggle上只有训练集提供了标签，所以只是用了训练集；如果数据集太大的话，我们出于模型训练时间因素的考虑，随机从数据集中删减掉了一部分；
2. 我们一般是按照训练集：验证集：测试集=9:1:10划分，不同的数据集具体划分比例不同。
